- job_name: 'ec2'
  metrics_path: /metrics
  static_configs:
    - targets: 
      - 52.15.71.241:9100
      - 52.15.71.241:80
      - 3.145.170.197:9100
      - 3.145.170.197:80
      - 18.221.221.225:9100
      - 18.221.221.225:80
- job_name: blackbox
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
      - http://52.15.71.241
      - http://3.145.170.197
      - http://18.221.221.225
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: prometheus-blackbox-exporter.monitoring:9115